if (NOT DEFINED INPUT OR "${INPUT}" STREQUAL "")
    message(FATAL_ERROR "NablaAssetManifestsMaterialize: INPUT is required")
endif()

if (NOT DEFINED DESTINATION OR "${DESTINATION}" STREQUAL "")
    message(FATAL_ERROR "NablaAssetManifestsMaterialize: DESTINATION is required")
endif()

function(_nam_materialize_file SOURCE_PATH DESTINATION_PATH)
    get_filename_component(_destination_dir "${DESTINATION_PATH}" DIRECTORY)
    file(MAKE_DIRECTORY "${_destination_dir}")
    if (EXISTS "${DESTINATION_PATH}" OR IS_SYMLINK "${DESTINATION_PATH}")
        file(REMOVE "${DESTINATION_PATH}")
    endif()

    if (NOT DEFINED LINK_MODE OR "${LINK_MODE}" STREQUAL "" OR LINK_MODE STREQUAL "copy")
        file(COPY_FILE "${SOURCE_PATH}" "${DESTINATION_PATH}" ONLY_IF_DIFFERENT)
    elseif(LINK_MODE STREQUAL "hardlink")
        file(CREATE_LINK "${SOURCE_PATH}" "${DESTINATION_PATH}" RESULT _result COPY_ON_ERROR)
        if (_result)
            message(FATAL_ERROR "NablaAssetManifestsMaterialize: failed to create hardlink from `${SOURCE_PATH}` to `${DESTINATION_PATH}`: ${_result}")
        endif()
    elseif(LINK_MODE STREQUAL "symlink")
        file(CREATE_LINK "${SOURCE_PATH}" "${DESTINATION_PATH}" SYMBOLIC RESULT _result COPY_ON_ERROR)
        if (_result)
            message(FATAL_ERROR "NablaAssetManifestsMaterialize: failed to create symlink from `${SOURCE_PATH}` to `${DESTINATION_PATH}`: ${_result}")
        endif()
    else()
        message(FATAL_ERROR "NablaAssetManifestsMaterialize: unsupported LINK_MODE `${LINK_MODE}`")
    endif()
endfunction()

_nam_materialize_file("${INPUT}" "${DESTINATION}")
