if (NOT DEFINED TYPE OR "${TYPE}" STREQUAL "")
    message(FATAL_ERROR "NablaAssetManifestsMaterialize: TYPE is required")
endif()

if (NOT DEFINED INPUT OR "${INPUT}" STREQUAL "")
    message(FATAL_ERROR "NablaAssetManifestsMaterialize: INPUT is required")
endif()

if (NOT DEFINED DESTINATION OR "${DESTINATION}" STREQUAL "")
    message(FATAL_ERROR "NablaAssetManifestsMaterialize: DESTINATION is required")
endif()

if (TYPE STREQUAL "file")
    get_filename_component(_destination_dir "${DESTINATION}" DIRECTORY)
    file(MAKE_DIRECTORY "${_destination_dir}")
    if (WIN32 OR (DEFINED NO_SYMLINKS AND NO_SYMLINKS))
        file(COPY_FILE "${INPUT}" "${DESTINATION}" ONLY_IF_DIFFERENT)
    else()
        if (EXISTS "${DESTINATION}" OR IS_SYMLINK "${DESTINATION}")
            file(REMOVE "${DESTINATION}")
        endif()
        file(CREATE_LINK "${INPUT}" "${DESTINATION}" SYMBOLIC COPY_ON_ERROR)
    endif()
elseif(TYPE STREQUAL "archive")
    if (EXISTS "${DESTINATION}")
        file(REMOVE_RECURSE "${DESTINATION}")
    endif()
    file(MAKE_DIRECTORY "${DESTINATION}")
    file(ARCHIVE_EXTRACT INPUT "${INPUT}" DESTINATION "${DESTINATION}")
else()
    message(FATAL_ERROR "NablaAssetManifestsMaterialize: unsupported TYPE `${TYPE}`")
endif()
