# Consumer module for the Nabla-Asset-Manifests repository.
#
# This module intentionally treats DVC metadata as the maintainer-facing source
# of truth. It does not expect any hand-written asset catalog.
#
# Consumer-side logic derives everything from:
# - the physical layout under a channel root such as `media/`
# - `.dvc` files generated by `dvc add`
# - GitHub release metadata for the selected backend tag

include_guard(GLOBAL)

function(_nam_log ENABLED MESSAGE_TEXT)
    if (ENABLED)
        message(STATUS "NablaAssetManifests: ${MESSAGE_TEXT}")
    endif()
endfunction()

function(_nam_summary MESSAGE_TEXT)
    message(STATUS "NablaAssetManifests: ${MESSAGE_TEXT}")
endfunction()

function(nam_get_repo_root OUT_VAR)
    if (DEFINED CMAKE_CURRENT_FUNCTION_LIST_DIR AND NOT "${CMAKE_CURRENT_FUNCTION_LIST_DIR}" STREQUAL "")
        get_filename_component(_root "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/.." ABSOLUTE)
    else()
        get_filename_component(_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
    endif()
    set(${OUT_VAR} "${_root}" PARENT_SCOPE)
endfunction()

function(nam_get_default_cache_root OUT_VAR)
    if (WIN32)
        if (DEFINED ENV{LOCALAPPDATA} AND NOT "$ENV{LOCALAPPDATA}" STREQUAL "")
            set(_base "$ENV{LOCALAPPDATA}")
        elseif(DEFINED ENV{USERPROFILE} AND NOT "$ENV{USERPROFILE}" STREQUAL "")
            set(_base "$ENV{USERPROFILE}/AppData/Local")
        else()
            nam_get_repo_root(_repo_root)
            set(_base "${_repo_root}/.nam-cache")
        endif()
    elseif(DEFINED ENV{XDG_CACHE_HOME} AND NOT "$ENV{XDG_CACHE_HOME}" STREQUAL "")
        set(_base "$ENV{XDG_CACHE_HOME}")
    elseif(DEFINED ENV{HOME} AND NOT "$ENV{HOME}" STREQUAL "")
        set(_base "$ENV{HOME}/.cache")
    else()
        nam_get_repo_root(_repo_root)
        set(_base "${_repo_root}/.nam-cache")
    endif()

    file(TO_CMAKE_PATH "${_base}/nabla/assets" _cache_root)
    set(${OUT_VAR} "${_cache_root}" PARENT_SCOPE)
endfunction()

function(nam_get_default_materialization_root OUT_VAR)
    if (DEFINED CMAKE_BINARY_DIR AND NOT "${CMAKE_BINARY_DIR}" STREQUAL "")
        set(_root "${CMAKE_BINARY_DIR}/nabla-assets-materialized")
    else()
        nam_get_repo_root(_repo_root)
        set(_root "${_repo_root}/_materialized")
    endif()
    set(${OUT_VAR} "${_root}" PARENT_SCOPE)
endfunction()

function(_nam_resolve_cache_root OUT_VAR)
    set(options)
    set(oneValueArgs CACHE_ROOT)
    cmake_parse_arguments(NAM "${options}" "${oneValueArgs}" "" ${ARGN})

    if (DEFINED NAM_CACHE_ROOT AND NOT "${NAM_CACHE_ROOT}" STREQUAL "")
        file(TO_CMAKE_PATH "${NAM_CACHE_ROOT}" _root)
    else()
        nam_get_default_cache_root(_root)
    endif()
    set(${OUT_VAR} "${_root}" PARENT_SCOPE)
endfunction()

function(_nam_get_channel_root OUT_VAR)
    set(options)
    set(oneValueArgs CHANNEL)
    cmake_parse_arguments(NAM "${options}" "${oneValueArgs}" "" ${ARGN})

    if (NOT NAM_CHANNEL)
        set(NAM_CHANNEL "media")
    endif()
    nam_get_repo_root(_repo_root)
    set(_channel_root "${_repo_root}/${NAM_CHANNEL}")
    if (NOT EXISTS "${_channel_root}")
        message(FATAL_ERROR "NablaAssetManifests: channel root `${_channel_root}` does not exist")
    endif()
    set(${OUT_VAR} "${_channel_root}" PARENT_SCOPE)
endfunction()

function(_nam_parse_dvc_file)
    set(options)
    set(oneValueArgs DVC_FILE CHANNEL OUT_KIND OUT_RELATIVE_PATH OUT_RELEASE_ASSET OUT_KEY)
    cmake_parse_arguments(NAM "${options}" "${oneValueArgs}" "" ${ARGN})

    if (NOT NAM_DVC_FILE)
        message(FATAL_ERROR "NablaAssetManifests: DVC_FILE is required")
    endif()

    _nam_get_channel_root(_channel_root CHANNEL "${NAM_CHANNEL}")
    file(STRINGS "${NAM_DVC_FILE}" _lines)

    set(_path "")
    set(_md5 "")
    foreach(_line IN LISTS _lines)
        if (_line MATCHES "^[ ]*path:[ ]+(.+)$")
            set(_path "${CMAKE_MATCH_1}")
        elseif(_line MATCHES "^[ ]*[-]?[ ]*md5:[ ]+(.+)$")
            set(_md5 "${CMAKE_MATCH_1}")
        endif()
    endforeach()

    if (_path STREQUAL "" OR _md5 STREQUAL "")
        message(FATAL_ERROR "NablaAssetManifests: failed to parse `${NAM_DVC_FILE}`")
    endif()

    get_filename_component(_dvc_dir "${NAM_DVC_FILE}" DIRECTORY)
    get_filename_component(_tracked_abs "${_dvc_dir}/${_path}" ABSOLUTE)
    file(RELATIVE_PATH _relative_path "${_channel_root}" "${_tracked_abs}")
    file(TO_CMAKE_PATH "${_relative_path}" _relative_path)

    if (_md5 MATCHES "\\.dir$")
        set(_kind "archive")
        get_filename_component(_name "${_tracked_abs}" NAME)
        set(_release_asset "${_name}.zip")
    else()
        set(_kind "file")
        get_filename_component(_release_asset "${_tracked_abs}" NAME)
    endif()

    set(${NAM_OUT_KIND} "${_kind}" PARENT_SCOPE)
    set(${NAM_OUT_RELATIVE_PATH} "${_relative_path}" PARENT_SCOPE)
    set(${NAM_OUT_RELEASE_ASSET} "${_release_asset}" PARENT_SCOPE)
    set(${NAM_OUT_KEY} "${_relative_path}" PARENT_SCOPE)
endfunction()

function(nam_get_channel_asset_keys OUT_VAR)
    set(options)
    set(oneValueArgs CHANNEL)
    cmake_parse_arguments(NAM "${options}" "${oneValueArgs}" "" ${ARGN})

    if (NOT NAM_CHANNEL)
        set(NAM_CHANNEL "media")
    endif()

    _nam_get_channel_root(_channel_root CHANNEL "${NAM_CHANNEL}")
    file(GLOB_RECURSE _dvc_files "${_channel_root}/*.dvc")
    list(SORT _dvc_files)

    set(_keys)
    foreach(_dvc IN LISTS _dvc_files)
        _nam_parse_dvc_file(
            DVC_FILE "${_dvc}"
            CHANNEL "${NAM_CHANNEL}"
            OUT_KIND _kind
            OUT_RELATIVE_PATH _relative_path
            OUT_RELEASE_ASSET _release_asset
            OUT_KEY _key
        )
        list(APPEND _keys "${_key}")
    endforeach()
    set(${OUT_VAR} "${_keys}" PARENT_SCOPE)
endfunction()

function(_nam_find_channel_asset)
    set(options)
    set(oneValueArgs CHANNEL ASSET OUT_KIND OUT_RELATIVE_PATH OUT_RELEASE_ASSET OUT_KEY)
    cmake_parse_arguments(NAM "${options}" "${oneValueArgs}" "" ${ARGN})

    if (NOT NAM_CHANNEL)
        set(NAM_CHANNEL "media")
    endif()
    if (NOT NAM_ASSET)
        message(FATAL_ERROR "NablaAssetManifests: ASSET is required")
    endif()

    _nam_get_channel_root(_channel_root CHANNEL "${NAM_CHANNEL}")
    file(GLOB_RECURSE _dvc_files "${_channel_root}/*.dvc")
    list(SORT _dvc_files)

    set(_match_count 0)
    foreach(_dvc IN LISTS _dvc_files)
        _nam_parse_dvc_file(
            DVC_FILE "${_dvc}"
            CHANNEL "${NAM_CHANNEL}"
            OUT_KIND _kind
            OUT_RELATIVE_PATH _relative_path
            OUT_RELEASE_ASSET _release_asset
            OUT_KEY _key
        )
        if (_key STREQUAL "${NAM_ASSET}" OR _release_asset STREQUAL "${NAM_ASSET}")
            math(EXPR _match_count "${_match_count}+1")
            set(_resolved_kind "${_kind}")
            set(_resolved_relative_path "${_relative_path}")
            set(_resolved_release_asset "${_release_asset}")
            set(_resolved_key "${_key}")
        endif()
    endforeach()

    if (_match_count EQUAL 0)
        message(FATAL_ERROR "NablaAssetManifests: unknown asset `${NAM_ASSET}` in channel `${NAM_CHANNEL}`")
    endif()
    if (_match_count GREATER 1)
        message(FATAL_ERROR "NablaAssetManifests: ambiguous asset selector `${NAM_ASSET}` in channel `${NAM_CHANNEL}`")
    endif()

    set(${NAM_OUT_KIND} "${_resolved_kind}" PARENT_SCOPE)
    set(${NAM_OUT_RELATIVE_PATH} "${_resolved_relative_path}" PARENT_SCOPE)
    set(${NAM_OUT_RELEASE_ASSET} "${_resolved_release_asset}" PARENT_SCOPE)
    set(${NAM_OUT_KEY} "${_resolved_key}" PARENT_SCOPE)
endfunction()

function(_nam_release_json_cache_key OUT_VAR REPO TAG)
    string(REPLACE "/" "__" _repo_key "${REPO}")
    set(${OUT_VAR} "NAM_RELEASE_JSON_${_repo_key}_${TAG}" PARENT_SCOPE)
endfunction()

function(_nam_get_backend_kind OUT_VAR)
    if (DEFINED NAM_BACKEND_KIND AND NOT "${NAM_BACKEND_KIND}" STREQUAL "")
        set(${OUT_VAR} "${NAM_BACKEND_KIND}" PARENT_SCOPE)
    else()
        set(${OUT_VAR} "github_release" PARENT_SCOPE)
    endif()
endfunction()

function(_nam_get_github_release_json OUT_JSON_VAR)
    set(options VERBOSE)
    set(oneValueArgs REPO TAG)
    cmake_parse_arguments(NAM "${options}" "${oneValueArgs}" "" ${ARGN})

    if (NOT DEFINED NAM_REPO OR "${NAM_REPO}" STREQUAL "")
        set(NAM_REPO "Devsh-Graphics-Programming/Nabla-Asset-Manifests")
    endif()
    if (NOT DEFINED NAM_TAG OR "${NAM_TAG}" STREQUAL "")
        set(NAM_TAG "media")
    endif()

    _nam_release_json_cache_key(_cache_key "${NAM_REPO}" "${NAM_TAG}")
    get_property(_cached_json GLOBAL PROPERTY "${_cache_key}")
    if (_cached_json)
        _nam_log("${NAM_VERBOSE}" "reusing cached release metadata for `${NAM_REPO}` tag `${NAM_TAG}`")
        set(${OUT_JSON_VAR} "${_cached_json}" PARENT_SCOPE)
        return()
    endif()

    _nam_resolve_cache_root(_cache_root)
    set(_meta_dir "${_cache_root}/meta/${NAM_REPO}")
    file(MAKE_DIRECTORY "${_meta_dir}")
    set(_json_file "${_meta_dir}/${NAM_TAG}.json")
    set(_api_url "https://api.github.com/repos/${NAM_REPO}/releases/tags/${NAM_TAG}")
    _nam_log("${NAM_VERBOSE}" "querying release metadata for `${NAM_REPO}` tag `${NAM_TAG}`")
    file(DOWNLOAD "${_api_url}" "${_json_file}" STATUS _status)
    list(GET _status 0 _status_code)
    if (NOT _status_code EQUAL 0)
        message(FATAL_ERROR "NablaAssetManifests: failed to query release metadata for `${NAM_REPO}` tag `${NAM_TAG}`")
    endif()
    file(READ "${_json_file}" _json)
    if (_json STREQUAL "")
        message(FATAL_ERROR "NablaAssetManifests: release metadata response for `${NAM_REPO}` tag `${NAM_TAG}` is empty")
    endif()
    set_property(GLOBAL PROPERTY "${_cache_key}" "${_json}")
    set(${OUT_JSON_VAR} "${_json}" PARENT_SCOPE)
endfunction()

function(_nam_find_github_release_asset OUT_DIGEST_VAR OUT_URL_VAR)
    set(options VERBOSE)
    set(oneValueArgs REPO TAG RELEASE_ASSET)
    cmake_parse_arguments(NAM "${options}" "${oneValueArgs}" "" ${ARGN})

    if (NOT DEFINED NAM_REPO OR "${NAM_REPO}" STREQUAL "")
        set(NAM_REPO "Devsh-Graphics-Programming/Nabla-Asset-Manifests")
    endif()
    if (NOT DEFINED NAM_TAG OR "${NAM_TAG}" STREQUAL "")
        set(NAM_TAG "media")
    endif()

    set(_verbose_args)
    if (NAM_VERBOSE)
        list(APPEND _verbose_args VERBOSE)
    endif()

    _nam_get_github_release_json(_json REPO "${NAM_REPO}" TAG "${NAM_TAG}" ${_verbose_args})
    string(JSON _asset_count LENGTH "${_json}" assets)
    if (_asset_count STREQUAL "")
        message(FATAL_ERROR "NablaAssetManifests: release `${NAM_TAG}` has no assets")
    endif()
    math(EXPR _asset_last "${_asset_count} - 1")
    foreach(_index RANGE ${_asset_last})
        string(JSON _name GET "${_json}" assets ${_index} name)
        if (_name STREQUAL "${NAM_RELEASE_ASSET}")
            string(JSON _digest GET "${_json}" assets ${_index} digest)
            string(JSON _url GET "${_json}" assets ${_index} browser_download_url)
            string(REPLACE "sha256:" "" _digest "${_digest}")
            set(${OUT_DIGEST_VAR} "${_digest}" PARENT_SCOPE)
            set(${OUT_URL_VAR} "${_url}" PARENT_SCOPE)
            return()
        endif()
    endforeach()
    message(FATAL_ERROR "NablaAssetManifests: release asset `${NAM_RELEASE_ASSET}` not found in `${NAM_REPO}` tag `${NAM_TAG}`")
endfunction()

function(_nam_resolve_remote_asset OUT_DIGEST_VAR OUT_URL_VAR)
    set(options VERBOSE)
    set(oneValueArgs REPO TAG RELEASE_ASSET)
    cmake_parse_arguments(NAM "${options}" "${oneValueArgs}" "" ${ARGN})

    _nam_get_backend_kind(_backend_kind)
    if (_backend_kind STREQUAL "github_release")
        set(_verbose_args)
        if (NAM_VERBOSE)
            list(APPEND _verbose_args VERBOSE)
        endif()
        _nam_find_github_release_asset(
            _resolved_digest
            _resolved_url
            REPO "${NAM_REPO}"
            TAG "${NAM_TAG}"
            RELEASE_ASSET "${NAM_RELEASE_ASSET}"
            ${_verbose_args}
        )
        set(${OUT_DIGEST_VAR} "${_resolved_digest}" PARENT_SCOPE)
        set(${OUT_URL_VAR} "${_resolved_url}" PARENT_SCOPE)
        return()
    endif()

    message(FATAL_ERROR "NablaAssetManifests: unsupported backend `${_backend_kind}`")
endfunction()

function(nam_fetch_asset)
    set(options VERBOSE)
    set(oneValueArgs CHANNEL REPO TAG ASSET CACHE_ROOT OUT_FILE OUT_STATUS)
    cmake_parse_arguments(NAM "${options}" "${oneValueArgs}" "" ${ARGN})

    if (NOT DEFINED NAM_REPO OR "${NAM_REPO}" STREQUAL "")
        set(NAM_REPO "Devsh-Graphics-Programming/Nabla-Asset-Manifests")
    endif()
    if (NOT DEFINED NAM_TAG OR "${NAM_TAG}" STREQUAL "")
        set(NAM_TAG "media")
    endif()
    if (NOT DEFINED NAM_CHANNEL OR "${NAM_CHANNEL}" STREQUAL "")
        set(NAM_CHANNEL "media")
    endif()
    if (NOT NAM_ASSET)
        message(FATAL_ERROR "NablaAssetManifests: ASSET is required for nam_fetch_asset")
    endif()

    _nam_find_channel_asset(
        CHANNEL "${NAM_CHANNEL}"
        ASSET "${NAM_ASSET}"
        OUT_KIND _kind
        OUT_RELATIVE_PATH _relative_path
        OUT_RELEASE_ASSET _release_asset
        OUT_KEY _key
    )

    set(_verbose_args)
    if (NAM_VERBOSE)
        list(APPEND _verbose_args VERBOSE)
    endif()

    _nam_resolve_remote_asset(
        _sha256
        _url
        REPO "${NAM_REPO}"
        TAG "${NAM_TAG}"
        RELEASE_ASSET "${_release_asset}"
        ${_verbose_args}
    )
    string(TOLOWER "${_sha256}" _sha256)

    _nam_resolve_cache_root(_cache_root CACHE_ROOT "${NAM_CACHE_ROOT}")
    set(_cache_file "${_cache_root}/blobs/${NAM_REPO}/${NAM_TAG}/${_release_asset}")
    set(_digest_file "${_cache_file}.sha256")
    get_filename_component(_cache_dir "${_cache_file}" DIRECTORY)
    file(MAKE_DIRECTORY "${_cache_dir}")

    _nam_log("${NAM_VERBOSE}" "fetch `${NAM_ASSET}` as `${_release_asset}` into cache root `${_cache_root}`")

    set(_need_download TRUE)
    set(_fetch_status "downloaded")
    if (EXISTS "${_cache_file}")
        if (EXISTS "${_digest_file}")
            file(READ "${_digest_file}" _cached_sha256)
            string(STRIP "${_cached_sha256}" _cached_sha256)
            string(TOLOWER "${_cached_sha256}" _cached_sha256)
        else()
            set(_cached_sha256 "")
        endif()

        if (_cached_sha256 STREQUAL "${_sha256}")
            _nam_log("${NAM_VERBOSE}" "cache hit for `${NAM_ASSET}`")
            set(_need_download FALSE)
            set(_fetch_status "cache_hit")
        else()
            if (NOT _cached_sha256 STREQUAL "")
                _nam_log("${NAM_VERBOSE}" "cache sidecar digest mismatch for `${NAM_ASSET}`")
            endif()
            file(SHA256 "${_cache_file}" _existing_sha256)
            string(TOLOWER "${_existing_sha256}" _existing_sha256)
            if (_existing_sha256 STREQUAL "${_sha256}")
                file(WRITE "${_digest_file}" "${_sha256}\n")
                _nam_log("${NAM_VERBOSE}" "cache hit after hash verification for `${NAM_ASSET}`")
                set(_need_download FALSE)
                set(_fetch_status "cache_hit")
            else()
                _nam_log("${NAM_VERBOSE}" "cache miss for `${NAM_ASSET}` because digest changed")
                file(REMOVE "${_cache_file}")
                if (EXISTS "${_digest_file}")
                    file(REMOVE "${_digest_file}")
                endif()
            endif()
        endif()
    endif()

    if (_need_download)
        _nam_log("${NAM_VERBOSE}" "downloading `${_release_asset}` from backend `${NAM_TAG}`")
        file(DOWNLOAD
            "${_url}"
            "${_cache_file}"
            EXPECTED_HASH "SHA256=${_sha256}"
            STATUS _status
            SHOW_PROGRESS
        )
        list(GET _status 0 _status_code)
        if (NOT _status_code EQUAL 0)
            message(FATAL_ERROR "NablaAssetManifests: failed to fetch `${NAM_ASSET}` from channel `${NAM_CHANNEL}`")
        endif()
        file(WRITE "${_digest_file}" "${_sha256}\n")
        _nam_log("${NAM_VERBOSE}" "stored `${NAM_ASSET}` in `${_cache_file}`")
    endif()

    if (DEFINED NAM_OUT_FILE AND NOT "${NAM_OUT_FILE}" STREQUAL "")
        set(${NAM_OUT_FILE} "${_cache_file}" PARENT_SCOPE)
    endif()
    if (DEFINED NAM_OUT_STATUS AND NOT "${NAM_OUT_STATUS}" STREQUAL "")
        set(${NAM_OUT_STATUS} "${_fetch_status}" PARENT_SCOPE)
    endif()
endfunction()

function(nam_materialize_asset)
    set(options VERBOSE)
    set(oneValueArgs CHANNEL REPO TAG ASSET CACHE_ROOT DESTINATION_ROOT MODE OUT_PATH OUT_STATUS)
    cmake_parse_arguments(NAM "${options}" "${oneValueArgs}" "" ${ARGN})

    if (NOT DEFINED NAM_REPO OR "${NAM_REPO}" STREQUAL "")
        set(NAM_REPO "Devsh-Graphics-Programming/Nabla-Asset-Manifests")
    endif()
    if (NOT DEFINED NAM_TAG OR "${NAM_TAG}" STREQUAL "")
        set(NAM_TAG "media")
    endif()
    if (NOT DEFINED NAM_CHANNEL OR "${NAM_CHANNEL}" STREQUAL "")
        set(NAM_CHANNEL "media")
    endif()
    if (NOT NAM_ASSET)
        message(FATAL_ERROR "NablaAssetManifests: ASSET is required for nam_materialize_asset")
    endif()
    if (NOT NAM_DESTINATION_ROOT)
        nam_get_default_materialization_root(NAM_DESTINATION_ROOT)
    endif()

    _nam_find_channel_asset(
        CHANNEL "${NAM_CHANNEL}"
        ASSET "${NAM_ASSET}"
        OUT_KIND _kind
        OUT_RELATIVE_PATH _relative_path
        OUT_RELEASE_ASSET _release_asset
        OUT_KEY _key
    )

    set(_verbose_args)
    if (NAM_VERBOSE)
        list(APPEND _verbose_args VERBOSE)
    endif()

    nam_fetch_asset(
        CHANNEL "${NAM_CHANNEL}"
        REPO "${NAM_REPO}"
        TAG "${NAM_TAG}"
        ASSET "${NAM_ASSET}"
        CACHE_ROOT "${NAM_CACHE_ROOT}"
        OUT_FILE _cache_file
        ${_verbose_args}
    )

    set(_target_path "${NAM_DESTINATION_ROOT}/${NAM_CHANNEL}/${_relative_path}")
    _nam_log("${NAM_VERBOSE}" "materialize `${NAM_ASSET}` to `${_target_path}`")
    if (_kind STREQUAL "file")
        get_filename_component(_target_dir "${_target_path}" DIRECTORY)
        file(MAKE_DIRECTORY "${_target_dir}")
        if (EXISTS "${_target_path}" OR IS_SYMLINK "${_target_path}")
            file(REMOVE "${_target_path}")
        endif()
        if (NAM_MODE STREQUAL "copy")
            file(COPY_FILE "${_cache_file}" "${_target_path}" ONLY_IF_DIFFERENT)
        else()
            file(CREATE_LINK "${_cache_file}" "${_target_path}" SYMBOLIC COPY_ON_ERROR)
        endif()
        set(_materialize_status "file")
    elseif(_kind STREQUAL "archive")
        if (EXISTS "${_target_path}")
            file(REMOVE_RECURSE "${_target_path}")
        endif()
        file(MAKE_DIRECTORY "${_target_path}")
        file(ARCHIVE_EXTRACT INPUT "${_cache_file}" DESTINATION "${_target_path}")
        set(_materialize_status "archive")
    else()
        message(FATAL_ERROR "NablaAssetManifests: unsupported asset kind `${_kind}`")
    endif()

    if (DEFINED NAM_OUT_PATH AND NOT "${NAM_OUT_PATH}" STREQUAL "")
        set(${NAM_OUT_PATH} "${_target_path}" PARENT_SCOPE)
    endif()
    if (DEFINED NAM_OUT_STATUS AND NOT "${NAM_OUT_STATUS}" STREQUAL "")
        set(${NAM_OUT_STATUS} "${_materialize_status}" PARENT_SCOPE)
    endif()
endfunction()

function(nam_fetch_channel)
    set(options VERBOSE)
    set(oneValueArgs CHANNEL REPO TAG CACHE_ROOT)
    set(multiValueArgs ITEMS)
    cmake_parse_arguments(NAM "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if (NOT DEFINED NAM_CHANNEL OR "${NAM_CHANNEL}" STREQUAL "")
        set(NAM_CHANNEL "media")
    endif()
    if (NOT DEFINED NAM_REPO OR "${NAM_REPO}" STREQUAL "")
        set(NAM_REPO "Devsh-Graphics-Programming/Nabla-Asset-Manifests")
    endif()
    if (NOT DEFINED NAM_TAG OR "${NAM_TAG}" STREQUAL "")
        set(NAM_TAG "media")
    endif()
    if (NAM_ITEMS)
        set(_items ${NAM_ITEMS})
    else()
        nam_get_channel_asset_keys(_items CHANNEL "${NAM_CHANNEL}")
    endif()

    list(LENGTH _items _item_count)
    _nam_log("${NAM_VERBOSE}" "fetch channel `${NAM_CHANNEL}` from repo `${NAM_REPO}` tag `${NAM_TAG}` with ${_item_count} item(s)")
    _nam_get_backend_kind(_backend_kind)
    _nam_resolve_cache_root(_resolved_cache_root CACHE_ROOT "${NAM_CACHE_ROOT}")
    _nam_summary("fetch start for channel `${NAM_CHANNEL}`: repo=`${NAM_REPO}`, tag=`${NAM_TAG}`, backend=`${_backend_kind}`, cache_root=`${_resolved_cache_root}`")

    set(_cache_hits 0)
    set(_downloads 0)
    set(_verbose_args)
    if (NAM_VERBOSE)
        list(APPEND _verbose_args VERBOSE)
    endif()

    foreach(_asset IN LISTS _items)
        nam_fetch_asset(
            CHANNEL "${NAM_CHANNEL}"
            REPO "${NAM_REPO}"
            TAG "${NAM_TAG}"
            ASSET "${_asset}"
            CACHE_ROOT "${NAM_CACHE_ROOT}"
            OUT_STATUS _fetch_status
            ${_verbose_args}
        )
        if (_fetch_status STREQUAL "cache_hit")
            math(EXPR _cache_hits "${_cache_hits}+1")
        elseif(_fetch_status STREQUAL "downloaded")
            math(EXPR _downloads "${_downloads}+1")
        endif()
    endforeach()

    _nam_summary("fetch summary for channel `${NAM_CHANNEL}`: total=${_item_count}, cache_hit=${_cache_hits}, download=${_downloads}")
endfunction()

function(nam_materialize_channel)
    set(options VERBOSE)
    set(oneValueArgs CHANNEL REPO TAG CACHE_ROOT DESTINATION_ROOT MODE)
    set(multiValueArgs ITEMS)
    cmake_parse_arguments(NAM "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if (NOT DEFINED NAM_CHANNEL OR "${NAM_CHANNEL}" STREQUAL "")
        set(NAM_CHANNEL "media")
    endif()
    if (NOT DEFINED NAM_REPO OR "${NAM_REPO}" STREQUAL "")
        set(NAM_REPO "Devsh-Graphics-Programming/Nabla-Asset-Manifests")
    endif()
    if (NOT DEFINED NAM_TAG OR "${NAM_TAG}" STREQUAL "")
        set(NAM_TAG "media")
    endif()
    if (NOT NAM_DESTINATION_ROOT)
        nam_get_default_materialization_root(NAM_DESTINATION_ROOT)
    endif()
    if (NAM_ITEMS)
        set(_items ${NAM_ITEMS})
    else()
        nam_get_channel_asset_keys(_items CHANNEL "${NAM_CHANNEL}")
    endif()

    list(LENGTH _items _item_count)
    _nam_log("${NAM_VERBOSE}" "materialize channel `${NAM_CHANNEL}` into `${NAM_DESTINATION_ROOT}` with ${_item_count} item(s)")
    _nam_summary("materialize start for channel `${NAM_CHANNEL}`: destination=`${NAM_DESTINATION_ROOT}`, mode=`${NAM_MODE}`")

    set(_file_count 0)
    set(_archive_count 0)
    set(_verbose_args)
    if (NAM_VERBOSE)
        list(APPEND _verbose_args VERBOSE)
    endif()

    foreach(_asset IN LISTS _items)
        nam_materialize_asset(
            CHANNEL "${NAM_CHANNEL}"
            REPO "${NAM_REPO}"
            TAG "${NAM_TAG}"
            ASSET "${_asset}"
            CACHE_ROOT "${NAM_CACHE_ROOT}"
            DESTINATION_ROOT "${NAM_DESTINATION_ROOT}"
            MODE "${NAM_MODE}"
            OUT_STATUS _materialize_status
            ${_verbose_args}
        )
        if (_materialize_status STREQUAL "file")
            math(EXPR _file_count "${_file_count}+1")
        elseif(_materialize_status STREQUAL "archive")
            math(EXPR _archive_count "${_archive_count}+1")
        endif()
    endforeach()

    _nam_summary("materialize summary for channel `${NAM_CHANNEL}`: total=${_item_count}, file=${_file_count}, archive=${_archive_count}, destination=`${NAM_DESTINATION_ROOT}`")
endfunction()

function(nam_fetch_and_materialize_channel)
    set(options VERBOSE)
    set(oneValueArgs CHANNEL REPO TAG CACHE_ROOT DESTINATION_ROOT MODE)
    set(multiValueArgs ITEMS)
    cmake_parse_arguments(NAM "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if (NOT DEFINED NAM_CHANNEL OR "${NAM_CHANNEL}" STREQUAL "")
        set(NAM_CHANNEL "media")
    endif()
    if (NOT DEFINED NAM_REPO OR "${NAM_REPO}" STREQUAL "")
        set(NAM_REPO "Devsh-Graphics-Programming/Nabla-Asset-Manifests")
    endif()
    if (NOT DEFINED NAM_TAG OR "${NAM_TAG}" STREQUAL "")
        set(NAM_TAG "media")
    endif()
    set(_verbose_args)
    if (NAM_VERBOSE)
        list(APPEND _verbose_args VERBOSE)
    endif()

    nam_fetch_channel(
        CHANNEL "${NAM_CHANNEL}"
        REPO "${NAM_REPO}"
        TAG "${NAM_TAG}"
        CACHE_ROOT "${NAM_CACHE_ROOT}"
        ITEMS ${NAM_ITEMS}
        ${_verbose_args}
    )

    nam_materialize_channel(
        CHANNEL "${NAM_CHANNEL}"
        REPO "${NAM_REPO}"
        TAG "${NAM_TAG}"
        CACHE_ROOT "${NAM_CACHE_ROOT}"
        DESTINATION_ROOT "${NAM_DESTINATION_ROOT}"
        MODE "${NAM_MODE}"
        ITEMS ${NAM_ITEMS}
        ${_verbose_args}
    )
endfunction()
