if (NOT DEFINED TYPE OR "${TYPE}" STREQUAL "")
    message(FATAL_ERROR "NablaAssetManifestsMaterialize: TYPE is required")
endif()

if (NOT DEFINED INPUT OR "${INPUT}" STREQUAL "")
    message(FATAL_ERROR "NablaAssetManifestsMaterialize: INPUT is required")
endif()

if (NOT DEFINED DESTINATION OR "${DESTINATION}" STREQUAL "")
    message(FATAL_ERROR "NablaAssetManifestsMaterialize: DESTINATION is required")
endif()

function(_nam_materialize_file SOURCE_PATH DESTINATION_PATH)
    get_filename_component(_destination_dir "${DESTINATION_PATH}" DIRECTORY)
    file(MAKE_DIRECTORY "${_destination_dir}")
    if (EXISTS "${DESTINATION_PATH}" OR IS_SYMLINK "${DESTINATION_PATH}")
        file(REMOVE "${DESTINATION_PATH}")
    endif()

    if (NOT DEFINED LINK_MODE OR "${LINK_MODE}" STREQUAL "" OR LINK_MODE STREQUAL "copy")
        file(COPY_FILE "${SOURCE_PATH}" "${DESTINATION_PATH}" ONLY_IF_DIFFERENT)
    elseif(LINK_MODE STREQUAL "hardlink")
        file(CREATE_LINK "${SOURCE_PATH}" "${DESTINATION_PATH}" RESULT _result COPY_ON_ERROR)
        if (_result)
            message(FATAL_ERROR "NablaAssetManifestsMaterialize: failed to create hardlink from `${SOURCE_PATH}` to `${DESTINATION_PATH}`: ${_result}")
        endif()
    elseif(LINK_MODE STREQUAL "symlink")
        file(CREATE_LINK "${SOURCE_PATH}" "${DESTINATION_PATH}" SYMBOLIC RESULT _result COPY_ON_ERROR)
        if (_result)
            message(FATAL_ERROR "NablaAssetManifestsMaterialize: failed to create symlink from `${SOURCE_PATH}` to `${DESTINATION_PATH}`: ${_result}")
        endif()
    else()
        message(FATAL_ERROR "NablaAssetManifestsMaterialize: unsupported LINK_MODE `${LINK_MODE}`")
    endif()
endfunction()

if (TYPE STREQUAL "file")
    _nam_materialize_file("${INPUT}" "${DESTINATION}")
elseif(TYPE STREQUAL "archive")
    if (NOT DEFINED EXTRACT_ROOT OR "${EXTRACT_ROOT}" STREQUAL "")
        message(FATAL_ERROR "NablaAssetManifestsMaterialize: EXTRACT_ROOT is required for archive mode")
    endif()
    if (NOT DEFINED HASH OR "${HASH}" STREQUAL "")
        message(FATAL_ERROR "NablaAssetManifestsMaterialize: HASH is required for archive mode")
    endif()

    set(_extract_dir "${EXTRACT_ROOT}/${HASH}")
    set(_extract_stamp "${_extract_dir}/.extract_complete")

    if (NOT EXISTS "${_extract_stamp}")
        if (EXISTS "${_extract_dir}")
            file(REMOVE_RECURSE "${_extract_dir}")
        endif()
        file(MAKE_DIRECTORY "${_extract_dir}")
        file(ARCHIVE_EXTRACT INPUT "${INPUT}" DESTINATION "${_extract_dir}")
        file(WRITE "${_extract_stamp}" "ok\n")
    endif()

    if (EXISTS "${DESTINATION}")
        file(REMOVE_RECURSE "${DESTINATION}")
    endif()
    file(MAKE_DIRECTORY "${DESTINATION}")

    file(GLOB_RECURSE _files RELATIVE "${_extract_dir}" "${_extract_dir}/*")
    foreach(_relative IN LISTS _files)
        set(_source_path "${_extract_dir}/${_relative}")
        set(_destination_path "${DESTINATION}/${_relative}")
        if (IS_DIRECTORY "${_source_path}")
            file(MAKE_DIRECTORY "${_destination_path}")
        else()
            _nam_materialize_file("${_source_path}" "${_destination_path}")
        endif()
    endforeach()
else()
    message(FATAL_ERROR "NablaAssetManifestsMaterialize: unsupported TYPE `${TYPE}`")
endif()
